export { OpenCodeClient } from "./OpenCodeClient";
export {
  OPENCODE_VERSION,
  DEFAULT_OPENCODE_URL,
  type OpenCodeEvent,
  type TextUpdatedEvent,
  type ToolUpdatedEvent,
  type SessionIdleEvent,
  type RuntimeErrorEvent,
  type OpenCodeClientOptions,
  type RuntimeStatus,
  type ToolCallStatus,
  type SessionMeta,
  type SkillInfo,
  type AgentInfo,
  type CommandInfo,
  type HistoryMessage,
  type ProviderInfo,
  type ProviderModelInfo,
  type ProviderAuthMethod,
  type ProviderCatalogEntry,
  type AuthPrompt,
  type OAuthAuthorization,
  type McpConfig,
  type McpServer,
  type QuestionOption,
  type QuestionItem,
  type QuestionAskedEvent,
  type QuestionResolvedEvent,
  type PermissionAskedEvent,
  type PermissionResolvedEvent,
  type PermissionReply,
} from "./types";

// Agent runtime abstraction layer (transport-neutral surface the UI targets).
// Re-exports the agent-runtime subpackage so consumers that already import
// from "@workbench/sdk" can opt in without changing their import path.
export {
  type AgentRuntime,
  type AgentRuntimeEvent,
  type AgentRuntimeConfig,
  type AgentRuntimeKind,
  type AgentSessionMeta,
  type AgentSkillInfo,
  type AgentCommandInfo,
  type AgentHistoryMessage,
  type AgentHistoryPart,
  type AgentProviderInfo,
  type AgentProviderModelInfo,
  type AgentMcpConfig,
  type AgentMcpServer,
  type PermissionMode,
  createAgentRuntime,
} from "./agent-runtime";
